# Generated by Django 5.1.6 on 2025-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/'),
        ),
    ]
